### PR TITLE
MBM-352 feature | add myrial machete

### PR DESCRIPTION
**Pull request by solidwaterslayer**

### CODE REVIEW

**Comment by MattKirchh** [comment]
@insertStringHere Is this all that needed to be done for the Myrial Machete? The 2h estimate makes it seem like it should be more complicated but I can't see, looking at the SRS, what else would need to be done.

**Comment by insertStringHere** [comment]
> @insertStringHere Is this all that needed to be done for the Myrial Machete? The 2h estimate makes it seem like it should be more complicated but I can't see, looking at the SRS, what else would need to be done.

pretty sure this is it; we just need the item built and I think my concern was not knowing how hard it would be to implement
@solidwaterslayer have you tested if the blade has durability when setting it to -1?

**Comment by MattKirchh** [comment]
> > @insertStringHere Is this all that needed to be done for the Myrial Machete? The 2h estimate makes it seem like it should be more complicated but I can't see, looking at the SRS, what else would need to be done.
> 
> pretty sure this is it; we just need the item built and I think my concern was not knowing how hard it would be to implement @solidwaterslayer have you tested if the blade has durability when setting it to -1?

I just tested and it does not lose any durability when it is set to -1.

**Comment by solidwaterslayer** [comment]
I tested my stuff this time. Sorry about the last few times.

**Review by insertStringHere — APPROVED** [review]

**Review by MattKirchh — APPROVED** [review]

**Pull request merged**
