### PR TITLE
Mbm 406 add jei support

### PR DESCRIPTION
**Pull request by insertStringHere**

### CODE REVIEW

**Comment by MattKirchh** [comment]
I'm getting a ton of errors when trying to launch the client.

image

**Comment by insertStringHere** [comment]
> I'm getting a ton of errors when trying to launch the client.
> 
> image

You'll have to rebuild and probably refresh IntelliJ's cache. I added a new package dependency to the gradle file

**Comment by MattKirchh** [comment]
> > I'm getting a ton of errors when trying to launch the client.
> > image
> 
> You'll have to rebuild and probably refresh IntelliJ's cache. I added a new package dependency to the gradle file

I did all that multiple times, still giving errors when attempting to compile. VSCode has the same behavior when executing the `runClient` task.

**Review by MattKirchh — APPROVED** [review]

**Review by griffinsellinger — APPROVED** [review]
built and tested - works well, recipes show up

**Pull request merged**
