### PR TITLE
MBM 22/366 - Add framework for configuration file and static values for player mana.

### PR DESCRIPTION
**Pull request by insertStringHere**
- [MBM-22 Added configuration classes](https://github.com/insertStringHere/MineBound/commit/027371dc57b46f5655c029c26855d0c9204e6477)
- [MBM-366 Add mana recovery data value.](https://github.com/insertStringHere/MineBound/commit/ba9c3937df8664d3a8c131aa0312243f0439a813)

### CODE REVIEW

**Comment by YonatanWN** [comment]
Does this auto-generate a config.yml and then reads it? How does this completely work?

**Comment by insertStringHere** [comment]
Yeah, it'll autogenerate a minebound-config.toml in the Minecraft world (because that's how server-side config values work in 1.18.2 now) using the default values, or read and update the fields in the classes if the file exists

**Comment by YonatanWN** [comment]
How would we read values off of the config?

**Comment by insertStringHere** [comment]
They become values in the config classes. maximumMana and manaRecovery will be accessible globally

**Review by griffinsellinger — APPROVED** [review]

**Review by MattKirchh — APPROVED** [review]

**Pull request merged**
