### PR TITLE
MBM-325 Light defensive tier one

### PR DESCRIPTION
**Pull request by MattKirchh**

### CODE REVIEW

**Comment by MattKirchh** [comment]
We need to decide how long we want a Magelight to last, if not indefinitely. Current placeholder from the prototype is 3 seconds.

**Comment by insertStringHere** [comment]
> We need to decide how long we want a Magelight to last, if not indefinitely. Current placeholder from the prototype is 3 seconds.

I think 5-10 minutes should be good. We also need to change the block to not be solid, like a torch or grass

**Comment by MattKirchh** [comment]
> > We need to decide how long we want a Magelight to last, if not indefinitely. Current placeholder from the prototype is 3 seconds.
> 
> I think 5-10 minutes should be good. We also need to change the block to not be solid, like a torch or grass

As in, a random time between 5 and 10 minutes?

**Comment by insertStringHere** [comment]
> > > We need to decide how long we want a Magelight to last, if not indefinitely. Current placeholder from the prototype is 3 seconds.
> > 
> > 
> > I think 5-10 minutes should be good. We also need to change the block to not be solid, like a torch or grass
> 
> As in, a random time between 5 and 10 minutes?

Nah, choose somewhere in that range. It's for lighting up caverns and stuff temporarily. We might also wanna make a config option to make it not destroy itself.

**Comment by MattKirchh** [comment]
> > > > We need to decide how long we want a Magelight to last, if not indefinitely. Current placeholder from the prototype is 3 seconds.
> > > 
> > > 
> > > I think 5-10 minutes should be good. We also need to change the block to not be solid, like a torch or grass
> > 
> > 
> > As in, a random time between 5 and 10 minutes?
> 
> Nah, choose somewhere in that range. It's for lighting up caverns and stuff temporarily. We might also wanna make a config option to make it not destroy itself.

Made the default 10 minutes and implemented the config for it.

**Review by solidwaterslayer — APPROVED** [review]

**Review by insertStringHere — APPROVED** [review]

**Review by insertStringHere — APPROVED** [review]

**Review by solidwaterslayer — APPROVED** [review]

**Pull request merged**
