### PR TITLE
MBM-319 Implemented electric utility all tiers

### PR DESCRIPTION
**Pull request by MattKirchh**
Also:
- Fixed bug with myrial machete (#110)
- Fixed mana text color in some tooltips
- Made elytra flight configurable for telekinetic utility spells
- Updated setting of NBT data

### CODE REVIEW

**Review by mnt43 — APPROVED** [review]

**Comment by insertStringHere** [comment]
Thorns effect does not work through Shield Utility; do we want that?
Also, there's no stacking when equipping electric modules. Is that something we'd want? Like boosting a tier 2 + tier 4 to speed 6?

**Comment by MattKirchh** [comment]
> Thorns effect does not work through Shield Utility; do we want that? 

Shield Utility doesn't have a thorns effect. Did you mean Shield Offensive?

> Also, there's no stacking when equipping electric modules. Is that something we'd want? Like boosting a tier 2 + tier 4 to speed 6?

I think that would be pretty fun to play with. I can make that change pretty easily if people are ok with that change.

**Comment by insertStringHere** [comment]
> > Thorns effect does not work through Shield Utility; do we want that?
> 
> Shield Utility doesn't have a thorns effect. Did you mean Shield Offensive?
> 
I mean the thorns effect on the armor from electric utility; enemies aren't damaged by it when you also have the shield on

**Comment by MattKirchh** [comment]
> > > Thorns effect does not work through Shield Utility; do we want that?
> > 
> > 
> > Shield Utility doesn't have a thorns effect. Did you mean Shield Offensive?
> 
> I mean the thorns effect on the armor from electric utility; enemies aren't damaged by it when you also have the shield on

Oh, yeah. That's because the Shield Utility spell cancels the damage event before it ever reaches the armor. We do that to prevent the player from getting hit back despite the attack being blocked.

**Review by insertStringHere — APPROVED** [review]

**Pull request merged**
