### PR TITLE
MBM 159/245 Myrial armor model part 1

### PR DESCRIPTION
**Pull request by insertStringHere**
Still have some fixes left to do, primarily for Mana Management to be unblocked

### CODE REVIEW

**Review by griffinsellinger — APPROVED** [review]
looks good

**Comment by MattKirchh** [comment]
Is this intentional?
image

**Comment by insertStringHere** [comment]
> Is this by design? image

Yeah, it _is_ armor still

**Comment by MattKirchh** [comment]
You can see the top of the legs when sprinting. These are covered by vanilla armor.

image

**Comment by MattKirchh** [comment]
You can ignore this if this texture clipping issue is known.

https://i.imgur.com/8oZit40.gif

**Review by MattKirchh — APPROVED** [review]

**Pull request merged**
