### PR TITLE
Added gilded diamond ingot texture

### PR DESCRIPTION
**Pull request by griffinsellinger**

### CODE REVIEW

**Review by insertStringHere — APPROVED** [review]
Looks good to me

**Review by insertStringHere — APPROVED** [review]

**Review by insertStringHere — CHANGES_REQUESTED** [review]
Could you add some darker pixels in the Myrial Diamond ingot's steel veins?

**Comment by YonatanWN** [comment]
Nice!

**Review by insertStringHere — APPROVED** [review]

**Review by YonatanWN — APPROVED** [review]
Nice

**Review by insertStringHere — APPROVED** [review]

**Pull request merged**
